project:
  type: website

website:
  announcement:
    icon: megaphone
    dismissable: true
    content: "**Alert - Both this website and the hackathon it relates to are in development.**"
    type: primary
    position: below-navbar
  title: ""
  navbar:
    background: "#4A5864"
    alignment: "right"
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - register.qmd
      - particpants.qmd
  back-to-top-navigation: true
  google-analytics:	G-9PNE3YLQDG
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

