project:
  type: website

execute:
  freeze: auto

website:
  announcement:
    icon: megaphone
    dismissable: true
    content: "Registration is closed now - check back for updates on the outputs of the Hackathon!"
    type: primary
    position: below-navbar

  title: ""

  # Logo section separate from navbar
  page-header:
    background: white  # White background behind the logo
    logo: images/logos.png  # Adjust the path to your logo
    logo-alt: "Hackathon Logo"  # Alternative text for accessibility

  navbar:
    background: "#4A5864"  # Background color of the navbar
    alignment: "center"  # Align the menu items in the center
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: particpants.qmd
        text: "Participants & Organisers"
      - href: preread.qmd
        text: "Pre-Hackathon Material"
      - href: schedule.qmd
        text: "Schedule"
      - href: materials.qmd
        text: "Presentations"
      - href: conference.qmd
        text: "Outcomes"
      - href: feedback.qmd
        text: "Daily Feedback"

  back-to-top-navigation: true
  google-analytics: G-N2S7VXS1QK

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
