project:
  type: website

execute:
  freeze: auto

website:
  announcement:
    icon: megaphone
    dismissable: true
    content: "Registration is closed now - check back for updates on the outputs of the Hackathon!"
    type: primary
    position: below-navbar

  title: "Bridging the Gap Hackathon - 20-24 January 2025, Nairobi, Kenya"

  navbar:
    background: "#4A5864"  # Background color for navbar (menu part)
    alignment: "center"  # Center align menu items
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: particpants.qmd
        text: "Participants & Organisers"
      - href: preread.qmd
        text: "Pre-Hackathon Material"
      - href: schedule.qmd
        text: "Schedule"
      - href: materials.qmd
        text: "Presentations"
      - href: conference.qmd
        text: "Outcomes"
      - href: feedback.qmd
        text: "Daily Feedback"

  back-to-top-navigation: true
  google-analytics: G-N2S7VXS1QK

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
