---
title: "Registration - Closed"
---

# Join us!

• **We want to**: Create free, open-source resources to support and facilitate evidence-informed decision making and address health policy needs in Kenya.

• **We are looking for**: 

  - **Public Health Decision-Makers:** Ministry of Health officials and public health specialists who provide insights based on real-world public health needs and ensure developed tools address practical challenges.

  - **Developers and Technical Experts:** Individuals proficient in R programming, version control using Git and GitHub, epidemiological modelling, and software development.

  - **Academics and Researchers:** Participants from various Kenyan institutions, not limited to CEMA, who are involved in infectious disease modelling and public health data analysis.

• **We aim to**: maximize diversity in skills, experiences, and people.

• **Applications close on the 5th December 2024**.

## Cost

There is no cost to attend the hackathon, however, there are a limited number of places available for the hackathon. While we do have some funds to support travel and attendance for participants from outside Nairobi and from MRC-GIDA at Imperial College London, these funds are limited. If you require financial support to attend, please indicate this in the registration form. 

## Registration

[**Registration Is Now Closed!**](/https://forms.gle/HaLCj3RaaC8E36UA9)

Please register your interest for the hackathon using the link above by 3 December 24. We will then be in touch to confirm participant funding and attendance, which will be allocated to ensure a diverse range of participants and backgrounds.

---
